### ISSUE TITLE
Template.yamlの分割

### ISSUE THREAD

**Issue by RyosukeDTomita** [RyosukeDTomita/ocn_daily_login_aws_lambda#16]
### idea

Template.yaml を毎回ビルドが必要なものと、それ以外で分けたい

毎回ビルドしないもの→S3,IAM
毎回ビルドしたいもの→Lambda,EventBridge,Lambda Layers

**Comment by RyosukeDTomita** [comment]
https://dev.classmethod.jp/articles/sam-template-api-gateway-def/
-t オプションでテンプレートを指定できそう

**Comment by RyosukeDTomita** [comment]
[ネストされたテンプレートを使う](https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/serverless-sam-template-nested-applications.html)ならば，承認がいるらしい?。
https://docs.aws.amazon.com/serverlessrepo/latest/devguide/acknowledging-application-capabilities.html

AWS SAMを使う場合には--CAPABILITY_IAM CAPABILITY_AUTO_EXPANDをつける

**Comment by RyosukeDTomita** [comment]
```
Resources:
  # DynamoDB用のテンプレートは別ファイルで参照
  DynamoDbStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: template_sub/template_dynamodb.yaml
      # 受け渡すパラメータを定義
      Parameters:
        StackName: !Ref AWS::StackName
        Env: !Ref Env
```

こんな感じでサブのテンプレートのパスを指定してネスト化できるみたいだが，今回の用途にはあわないので使わない。
S3やIAMを毎回再生成するのがめんどくさいためテンプレートを分けているため，依存性があると困る。
この機能はあくまでテンプレートをネスト化するためのものだと思われる。
